services:
  - type: cron
    name: pepe-signal-bot
    env: python
    plan: free
    schedule: '*/5 * * * *'
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
